import Button from "@/components/Button";
import ModalCreateInventory from "@/components/ModalCreateInventory";
import ModalTemplate, { ModalTemplateHandles } from "@/components/ModalTemplate";
import Navigation from "@/components/Navigation";
import Table from "@/components/Table";
import TitlePage from "@/components/TitlePage";
import { InvertoryInterface, getAllInventorys } from "@/services/Inventory";
import PageContainer from "@/templates/PageContainer";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import styled from "styled-components";

export default function Home() {
  const [inventorys, setInventorys] = useState<InvertoryInterface[]>([]);
  const modalRef = useRef<ModalTemplateHandles>(null)

  useEffect(() => {
    getAllInventorys().then((res) => setInventorys(res.data));
  }, []);

  function addInventory(data: InvertoryInterface){
    setInventorys([data,...inventorys])
  }

  return (
    <>
      <Head>
        <title>Estoque - MeuEstoque</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>

        <ModalCreateInventory ref={modalRef} setInventory={addInventory}/>
        <Row>
          <TitlePage>Estoque</TitlePage>
          <Button onClick={()=> modalRef.current?.openModal()}>Novo produto</Button>
        </Row>

        <Table header={["ID","Nome", "Quantidade", "Preço"]}>
          {inventorys.map((item) => (
            <tr className="c-table__row" key={item.id}>
              <td className="c-table__row__data">{item.id}</td>
              <td className="c-table__row__data">{item.name}</td>
              <td className="c-table__row__data">{item.quantity}</td>
              <td className="c-table__row__data">{item.price}</td>
            </tr>
          ))}
        </Table>
      </PageContainer>
    </>
  );
}

const Row = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 32px;
`;

