import Navigation from "@/components/Navigation";
import ProductRowTable from "@/components/ProductRowTable";
import Table from "@/components/Table";
import TitlePage from "@/components/TitlePage";
import { getInventoysByIds, InvertoryInterface } from "@/services/Inventory";
import { getAllSales, Sales, SalesProduct } from "@/services/Sales";
import PageContainer from "@/templates/PageContainer";
import { formatedDate, formatPrice } from "@/utils/formatedDate";
import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";

export default function Home() {
  const [sales, setSales] = useState<Sales[]>([]);

  useEffect(() => {
    getAllSales().then((res) => setSales(res.data));
  }, []);

  function formatedValue(list: SalesProduct[]) {
    let value = 0;

    list.map((item) => {
      value += item.unit_value * item.quantity;
    });

    return formatPrice(value);
  }

  return (
    <>
      <Head>
        <title>Vendas - MeuEstoque</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <Row>
          <TitlePage>Vendas</TitlePage>
        </Row>
        <Table header={["ID", "Produtos", "Valor Total", "Data"]}>
          {sales.map((item) => (
            <tr className="c-table__row" key={item.id}>
              <td className="c-table__row__data">{item.id}</td>
              <ProductRowTable list={item.produtos} />
              <td className="c-table__row__data">
                {formatedValue(item.produtos)}
              </td>
              <td className="c-table__row__data">
                {formatedDate(item.date_sold)}
              </td>
            </tr>
          ))}
        </Table>
      </PageContainer>
    </>
  );
}

const Row = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 32px;
`;
